"""
Django settings for contractor_crm_backend project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from celery.schedules import crontab
from datetime import timedelta
from decouple import config
import os
import dj_database_url



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR =  os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&dse1c2s@8zio8t5^)lsy$af^*8(+#@h^#eptk^e3xva=#xqk*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['ecc-backend-8684636373f0.herokuapp.com','127.0.0.1', 'localhost', 'b9d7-216-249-49-34.ngrok-free.app', '6b1f-216-249-49-34.ngrok-free.app']


AUTH_USER_MODEL = 'contractors.User'  # Replace 'your_app' with the app where User is defined


CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    "https://ecc-frontend-0ce8d42f6dc5.herokuapp.com",
]
CSRF_COOKIE_NAME = 'csrftoken'
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
]

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Default session engine
SESSION_COOKIE_NAME = 'sessionid'  # The name of the session cookie
SESSION_EXPIRE_AT_BROWSER_CLOSE = False 
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'contractors',
    'django_celery_beat',
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework.authtoken',
    'channels',
    'django_extensions',
    'drf_yasg',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',

    
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
     'whitenoise.middleware.WhiteNoiseMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = False 

ROOT_URLCONF = 'contractor_crm_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#WSGI_APPLICATION = 'contractor_crm_backend.wsgi.application'
ASGI_APPLICATION = 'contractor_crm_backend.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': dj_database_url.config(default=os.environ.get('DATABASE_URL'))
}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'contractor_crm_db',    # Name of the PostgreSQL database you created
        'USER': 'crm_user',          # PostgreSQL username
        'PASSWORD': 'ammar2003',  # PostgreSQL password
        'HOST': 'localhost',             # Database host, 'localhost' if running locally
        'PORT': '5432',                  # PostgreSQL port (default is 5432)
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
 # Adjust this based on where you placed your React build files


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

CELERY_BEAT_SCHEDULE = {
    'send-invoice-reminders-everyday': {
        'task': 'contractors.tasks.send_invoice_reminders',
        'schedule': crontab(hour=0, minute=0),  # Every day at midnight
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Keep JWT for token-based authentication if needed
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
     "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FormParser",
    ],
}

LOGIN_URL = '/api/login/'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


SESSION_COOKIE_AGE = 1209600  # Two weeks in seconds (2 weeks)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

LOGIN_REDIRECT_URL = '/home/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Replace with your SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'ammarogeil@gmail.com'  # Your email address
EMAIL_HOST_PASSWORD = 'fchg qwmy agvt klxa'  # Your email password


DOCUSIGN_AUTH_URL = "https://account-d.docusign.com/oauth/auth"
TOKEN_URL = "https://account-d.docusign.com/oauth/token"
DOCUSIGN_BASE_PATH = "https://demo.docusign.net/restapi"  # Use production URL in production
CLIENT_ID = "a0769e40-cd97-4e92-a79b-8021247aeaf3"
CLIENT_SECRET = "0f55b6ae-77d3-4271-b58c-8a757095da53"
REDIRECT_URI = "http://localhost:8000/docusign/callback"

DOCUSIGN = {
    "INTEGRATION_KEY": "a0769e40-cd97-4e92-a79b-8021247aeaf3",
    "USER_ID": "31467551",
    "PRIVATE_KEY": "0f55b6ae-77d3-4271-b58c-8a757095da53",
    "BASE_PATH": "http://localhost:8000/docusign/callback",  # Sandbox
    "ACCOUNT_ID": "31467551",
}

STRIPE_SECRET_KEY = 'sk_test_51QSiGBF7wkMLsTtpa5iRWHQjKTh3EhBrCJMHnqlDaGNVgN7lUx8SYXHgwowaqGRMFwRenqjm1lF0dWQdKw6BiI3V00UNbrSWcd'
STRIPE_PUBLISHABLE_KEY = 'pk_test_51QSiGBF7wkMLsTtpBBzTCQOPHg8otgHraZEnvAO7Tqv1U6vdERKvFIjAfdykTzcZqE8z50u7N69Qspz4Sk4gpbvm00bGltNgjo'


CSP_STYLE_SRC = ["'self'", "'unsafe-inline'", "https://*.stripe.com"]
CSP_SCRIPT_SRC = ["'self'", "https://js.stripe.com"]
CSP_CONNECT_SRC = ["'self'", "https://api.stripe.com", "https://*.stripe.com"]


