# Generated by Django 5.1.1 on 2024-10-03 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0005_payment_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('signed_at__isnull', False), ('status', 'Completed')), name='completed_contract_must_be_signed'),
        ),
    ]
