# Generated by Django 5.1.1 on 2024-10-14 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0006_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contractors.client'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contractor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contractors.contractor'),
        ),
    ]
