# Generated by Django 5.1.1 on 2024-10-16 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0007_invoice_client_invoice_contractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('job_type_association', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='contractors.quizquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ClientQuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.client')),
                ('selected_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.quizanswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.quizquestion')),
            ],
        ),
    ]
