# Generated by Django 5.1.1 on 2024-10-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='profile_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
