# Generated by Django 5.1.1 on 2024-10-29 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0011_contractor_profile_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_contract', 'Create Contract'), ('update_profile', 'Update Profile'), ('send_payment', 'Send Payment')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('target_object', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contractors.user')),
            ],
        ),
    ]
