# Generated by Django 5.1.3 on 2024-11-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0013_alter_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
    ]
