# Generated by Django 5.1.3 on 2024-11-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0015_alter_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='selected_choice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='choices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Answer'), ('multiple_choice', 'Multiple Choice')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
