# Generated by Django 5.1.3 on 2024-11-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0016_formresponse_selected_choice_quiz_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='contractor_pictures/'),
        ),
    ]
