# Generated by Django 5.1.3 on 2024-12-02 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0019_remove_message_chat_room_message_read_conversation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='client',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
