# Generated by Django 5.1.3 on 2024-12-05 21:28

import contractors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0022_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=contractors.models.User),
        ),
    ]
