# Generated by Django 5.1.3 on 2024-12-12 19:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0024_alter_contractor_location_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
