# Generated by Django 5.1.3 on 2024-12-12 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0025_servicerequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contract',
            name='completed_contract_must_be_signed',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='details',
            new_name='terms',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='client',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='signed_at',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='status',
        ),
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
