# Generated by Django 5.1.3 on 2024-12-12 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0026_remove_contract_completed_contract_must_be_signed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_signed', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_contracts', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.contract')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
