# Generated by Django 5.1.3 on 2024-12-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0027_sentcontract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='rating',
        ),
        migrations.AddField(
            model_name='contractor',
            name='total_ratings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractor',
            name='total_ratings_sum',
            field=models.IntegerField(default=0),
        ),
    ]
