# Generated by Django 5.1.3 on 2024-12-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0028_remove_contractor_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
