# Generated by Django 5.1.3 on 2024-12-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0030_contractor_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
