# Generated by Django 5.1.3 on 2024-12-17 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0033_contractorapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='terms',
            new_name='content',
        ),
    ]
