# Generated by Django 5.1.3 on 2024-12-17 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0034_rename_terms_contract_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='created_at',
            new_name='sent_at',
        ),
        migrations.AlterField(
            model_name='contractconsent',
            name='contract_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='contractors.contract'),
        ),
    ]
