# Generated by Django 5.1.3 on 2024-12-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0035_rename_created_at_contract_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractconsent',
            name='contract_id',
            field=models.ForeignKey(to='contractors.Contract', on_delete=models.CASCADE, related_name='consents'),
        ),
        migrations.RenameField(
            model_name='contractconsent',
            old_name='contract_id',
            new_name='contract',
        ),
    ]
