# Generated by Django 5.1.3 on 2024-12-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0036_rename_contract_id_contractconsent_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
    ]
