# Generated by Django 5.1.3 on 2024-12-18 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0038_contract_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_contracts_from_contracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
