# Generated by Django 5.1.3 on 2025-01-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0039_contract_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorapplication',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=255),
        ),
    ]
