# Generated by Django 5.1.3 on 2025-01-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0040_contractorapplication_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='tutorials/videos/')),
                ('thumbnail', models.ImageField(upload_to='tutorials/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
