# Generated by Django 5.1.3 on 2025-01-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0041_tutorials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='experience_years',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='job_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='total_ratings_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='total_ratings_sum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
