# Generated by Django 5.1.3 on 2025-01-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0042_alter_contractor_experience_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorials',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutorials',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='tutorials/thumbnails/'),
        ),
    ]
