# Generated by Django 5.1.3 on 2025-01-31 22:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0043_tutorials_likes_tutorials_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorials',
            name='likes',
        ),
        migrations.AddField(
            model_name='tutorials',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_tutorials', to=settings.AUTH_USER_MODEL),
        ),
    ]
