# Generated by Django 5.1.3 on 2025-02-03 19:50

import contractors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0044_remove_tutorials_likes_tutorials_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='video',
            field=models.FileField(upload_to='tutorials/videos/', validators=[contractors.models.validate_video_or_image]),
        ),
    ]
