# Generated by Django 5.1.3 on 2025-02-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0046_blog_blogreply_blog_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorials',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
