# Generated by Django 5.1.3 on 2025-02-26 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0047_tutorials_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorials',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to=settings.AUTH_USER_MODEL),
        ),
    ]
