# Generated by Django 5.1.3 on 2025-03-17 18:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0050_alter_tutorials_thumbnail_alter_tutorials_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='answer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='answer_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Answer'), ('multiple_choice', 'Multiple Choice'), ('date', 'Date Picker'), ('text_with_image', 'Text Answer with Optional Image')], default='text', max_length=20),
        ),
    ]
